#!/bin/sh
#

load_drivers()
{
	echo "Loading arm-ffa-tee..."
	if ! grep -qs 'arm-ffa-tee' /proc/modules; then
		insmod /root/arm-ffa-tee.ko
	fi
}

start_tee_supplicant()
{
	echo "Starting tee-supplicant daemon..."
	tee-supplicant -d
}

case "$1" in
	start)
		load_drivers
		start_tee_supplicant
		;;
	stop)
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
